# Generated by Django 2.1.5 on 2019-01-31 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warrior1', models.FileField(upload_to='codes/')),
                ('warrior2', models.FileField(upload_to='codes/')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='current_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeguru_app.Code'),
        ),
    ]
