# Generated by Django 2.1.5 on 2019-01-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru_app', '0002_auto_20190131_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='current_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codeguru_app.Code'),
        ),
    ]
