# Generated by Django 2.1.5 on 2019-02-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru_app', '0007_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
