# Generated by Django 2.1.5 on 2019-02-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru_app', '0008_auto_20190207_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rounds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
