# Generated by Django 2.1.5 on 2019-02-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru_app', '0003_auto_20190131_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeguru_app.Code')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='current_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeguru_app.Code'),
        ),
        migrations.AddField(
            model_name='result',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeguru_app.Team'),
        ),
    ]
