# Generated by Django 2.1.5 on 2019-02-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru_app', '0004_auto_20190206_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
