# Generated by Django 2.1.5 on 2019-03-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru_app', '0009_auto_20190209_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='warrior1',
            field=models.FileField(default='codes/default.s', upload_to='codes/'),
        ),
        migrations.AlterField(
            model_name='code',
            name='warrior2',
            field=models.FileField(default='codes/default.s', upload_to='codes/'),
        ),
    ]
