# Generated by Django 2.1.7 on 2019-03-03 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru_app', '0010_auto_20190303_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='current_code',
        ),
        migrations.AddField(
            model_name='code',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codeguru_app.Team'),
            preserve_default=False,
        ),
    ]
