# Generated by Django 2.1.7 on 2019-03-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru_app', '0011_auto_20190303_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='code',
            name='warrior1',
            field=models.FileField(upload_to='codes/'),
        ),
        migrations.AlterField(
            model_name='code',
            name='warrior2',
            field=models.FileField(upload_to='codes/'),
        ),
    ]
